block_labels = ["needs-decision"]
delete_merged_branches = true
required_approvals = 1
status = [
    "ci-linux (stable)",
    "ci-linux (1.42.0)",
    "build-other (macOS-latest)",
    "build-other (windows-latest)",
    "Rustfmt"
]
