MEMORY
{
    RAM : ORIGIN = 0x80000000, LENGTH = 16K
    FLASH : ORIGIN = 0x20000000, LENGTH = 4M
}

REGION_ALIAS("REGION_TEXT", FLASH);
REGION_ALIAS("REGION_RODATA", FLASH);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", RAM);

{% if contains(cfg.feature, "trap-region") %}
REGION_ALIAS("REGION_TRAP", RAM);
{% endif %}
