on:
  push:
    branches: [ master ]
    paths-ignore:
      - "**/*.md"
      - "*.md"
      - "typos.toml"
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "*.md"
      - "typos.toml"
  merge_group:
    paths-ignore:
      - "**/*.md"
      - "*.md"
      - "typos.toml"

name: Code formatting check

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Run Rustfmt
        run: cargo fmt --all -- --check --verbose
