on:
  push:
    branches: [ master ]
    paths-ignore:
      - "**/*.md"
      - "README*"
      - "LICENSE*"
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "README*"
      - "LICENSE*"
  merge_group:
    paths-ignore:
      - "**/*.md"
      - "README*"
      - "LICENSE*"

name: Spelling Check

jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: typos
      uses: crate-ci/typos@master
