on:
  push:
    branches: [ master ]
    paths-ignore:
      - "**/*.md"
      - "*.md"
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "*.md"
      - "typos.toml"
  merge_group:
    paths-ignore:
      - "**/*.md"
      - "*.md"
      - "typos.toml"

name: Spelling Check

jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: typos
      uses: crate-ci/typos@master
